spring:
  mail:
    Host: smtp.mailtrap.io
    Port: 2525
    Username: 1729bf0f00cdfe
    Password: cb20d16da97fd0
  data:
    mongodb:
      host: localhost
      port: 27017
      database: TestSubmDB

  jackson:
    default-property-inclusion: NON_NULL


# Enable Logging mongo queries
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG


javers:
  documentDbCompatibilityEnabled: false
  objectAccessHook: org.javers.spring.mongodb.DBRefUnproxyObjectAccessHook
  snapshotsCacheSize: 5000

  spring:
    h2:
      console:
        enabled: true

  server:
      port: 9192

